layout_spectrum: 0.5440639
typography_spectrum: 0.08981876
color:
  saturation: 0.367004
  lightness: 0.2891682
  brandStrength: 0.7434074
  rhythmicContrast: 0.3029774
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
name: Laura Luck
